server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        #server-addr: localhost:8848
        server-addr: 10.1.1.115:1111
management:
  endpoints:
    web:
      exposure:
        include: '*'